//
//  ChatModels.swift
//  SBChat
//
//  Created by Jakob Mikkelsen on 5/29/18.
//  Copyright (c) 2018 SecondBook. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Chat
{
    // MARK: Use cases

    enum Send
    {
        struct Request
        {
            let message: ChatMessage
            let room: ChatRoom
        }
        struct Response
        {
            let error: Error?
        }
        struct ViewModel
        {
            let error: Error?
        }
    }
}

