//
//  ChatPresenter.swift
//  SBChat
//
//  Created by Jakob Mikkelsen on 5/29/18.
//  Copyright (c) 2018 SecondBook. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatPresentationLogic
{
    func presentSomething(response: Chat.Something.Response)
}

class ChatPresenter: ChatPresentationLogic
{
    weak var viewController: ChatDisplayLogic?

    // MARK: Do something

    func presentSomething(response: Chat.Something.Response)
    {
        let viewModel = Chat.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}

