//
//  ChatInteractor.swift
//  SBChat
//
//  Created by Jakob Mikkelsen on 5/29/18.
//  Copyright (c) 2018 SecondBook. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatBusinessLogic
{
    func sendMessage(request: Chat.Send.Request)
}

protocol ChatDataStore
{
    //var name: String { get set }
}

class ChatInteractor: ChatBusinessLogic, ChatDataStore
{
    var presenter: ChatPresentationLogic?
    var worker: ChatWorker?

    // MARK: Send Message
    func sendMessage(request: Chat.Send.Request)
    {
        worker = ChatWorker()
        worker?.sendMessage(message: request.message, chatRoom: request.room, completion: { [weak self] (error) in
            let response = Chat.Send.Response(error: error)
            self?.presenter?.presentSendMessage(response: response)
        })
    }
}

