//
//  ChatWorker.swift
//  SBChat
//
//  Created by Jakob Mikkelsen on 5/29/18.
//  Copyright (c) 2018 SecondBook. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MessageKit

class ChatWorker {

    let currentDriver = FirebaseDriver()

    /// Send message to roomID
    func sendMessage(message: ChatMessage, chatRoom: ChatRoom, completion: @escaping (_ error: Error?) -> Void) {
        currentDriver.sendMessage(message: message, forChatRoom: chatRoom) { (error) in
            completion(error)
        }
    }

    /// Fetch messages for roomID
    func fetchMessages(forChatRoom chatRoom: ChatRoom, completion: @escaping (_ chatMessages: [ChatMessage], _ error: Error?) -> Void) {
        currentDriver.fetchMessages(forChatRoom: chatRoom) { (messages) in
            completion(messages, nil)
        }
    }

}

